### ISSUE TITLE
Can't find _config.yml

### ISSUE THREAD

**Issue by hourback** [spf13/herring-cove#2]
Hi there!

Enthusiastically new to Hugo and anxious to learn stuff.  I settled on the herring-cove theme and see in the readme that I should edit the "_config.yml", but I don't see one.  Is it supposed to exist in the theme package already, or do I need to create it?  If I need to create it, where does it belong?

Thanks in advance.

**Comment by cbgrey** [comment]
I ended up here with the same question/problem.

**Comment by mbollemeijer** [comment]
Example config:
https://github.com/mbollemeijer/mbollemeijer.github.io/blob/master/source/config.yaml

you can just name it config.

**Comment by cbgrey** [comment]
Based on this:
http://gohugo.io/overview/configuration/

It looks like your example is the global Hugo config file. Is that all one in the same? Meaning, the template setting can (and do) just go in there?

**Comment by mbollemeijer** [comment]
Yhea, you can specify your template settings in the same config.yaml

**Comment by cbgrey** [comment]
Excellent, thank you. As far as I'm concerned that closes this issue.

**Comment by mbollemeijer** [comment]
No problem, glad I could be of assistance
